### ISSUE TITLE
Some qestions

### ISSUE THREAD

**Issue by Deadmin1** [thanhhau097/chargrid2d#4]
Hi,

i have some question about your project here. Is this an implementation of the paper: 
https://arxiv.org/pdf/1809.08799v1.pdf
Chargrid: Towards Understanding 2D Documents

Im working on recreating this paper and have some problems. 
Thanks in advance

**Comment by thanhhau097** [comment]
yes, it is an implementation of that paper, please be careful with the label inputs in generate_mask.py file.
