### ISSUE TITLE
example train data

### ISSUE THREAD

**Issue by jamesguo** [thanhhau097/chargrid2d#6]
Can you please provide one demo Labelling data

**Comment by lionelcinnamon** [comment]
{
  "file_name": "1231231.png",
  "attributes": {
    "_via_img_metadata": {
      "regions": [
        {
          "shape_attributes": {
            "name": "rect",
            "x": 1256,
            "y": 99,
            "width": 310,
            "height": 37
          },
          "region_attributes": {
            "label": "12367162783",
            "key_type": "other",
            "text_category": "japanese",
            "text_type": "printed",
            "formal_key": "",
            "note": ""
          }
        }
      ],
      "file_attributes": {}
    },
    "_via_attributes": {
      "region": {
        "label": {
          "type": "text",
          "description": "",
          "default_value": ""
        },
        "key_type": {
          "type": "dropdown",
          "description": "",
          "options": {
            "key": "",
            "value": "",
            "common_key": "",
            "master_key": "",
            "other": ""
          },
          "default_options": {
            "other": "true"
          }
        },
        "text_category": {
          "type": "dropdown",
          "description": "",
          "options": {
            "name": "",
            "address": "",
            "email": "",
            "number": "",
            "alphabet": "",
            "japanese": "",
            "checkbox": "",
            "mix": ""
          },
          "default_options": {
            "japanese": "true"
          }
        },
        "text_type": {
          "type": "dropdown",
          "description": "",
          "options": {
            "handwriting": "",
            "printed": "",
            "mixed": ""
          },
          "default_options": {
            "printed": "true"
          }
        },
        "formal_key": {
          "type": "text",
          "description": "",
          "default_value": ""
        },
        "note": {
          "type": "text",
          "description": "",
          "default_value": ""
        }
      },
      "file": {}
    }
  }
}

**Comment by GadekarSid** [comment]
Hi,

Can you please share the sample file as well? Makes it easier to visualize.

**Comment by thanhhau097** [comment]
Could you check the `icdar` branch? That branch is currently using SROIE dataset

**Comment by thanhhau097** [comment]
I've just updated the README.
