### ISSUE TITLE
steps to execute the code

### ISSUE THREAD

**Issue by rr370ba** [thanhhau097/chargrid2d#7]
Thanks for putting up the implementation of Chargrid. Kindly explain the steps to execute the code if I have set of invoice images with annotation of relevant areas which need to be extracted. I don't have the exact labels of those designated areas in a json file.

**Comment by thanhhau097** [comment]
As I said in the README file, you should consider the function def __convert_data(self, label_json): in https://github.com/thanhhau097/chargrid2d/blob/master/dataloader_utils/generate_mask.py#L27 based on your input format, as long as the outputs of this function is correct. (sorry for this mistake, I will update code for public dataset later)

To train model, first you need to run chargrid2d/dataloader_utils/generate_mask.py to generate data to train segmentation model from bounding box and text.

Then you need to run train.py file to train the model.

**Comment by thanhhau097** [comment]
I've just updated the README.
