### ISSUE TITLE
Bounding Box Regression Ground Truth

### ISSUE THREAD

**Issue by rudi77** [thanhhau097/chargrid2d#9]
Hi, thanks for sharing you chargrid code. I read the chargrid paper but I'm a bit confused about the anchor box representation and the corresponding bounding box representation. How do you generate the ground truths for the bounding box regression decoder?

**Comment by ndhung** [comment]
Hi @rudi77, we haven't implemented box regression yet. However, I think it just like object detection problems. We will implement it when we have free time.
